name: test

on:
  push:

jobs:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: '3.10'
      cache: 'pip' # caching pip dependencies
  - run: pip install -r requirements.txt
